version: 0.0.14
commit: '%.%.%'
files:
  README.md:
    - 'https://deno.land/x/dxx@v%.%.%'
    - 'https://cdn.jsdelivr.net/gh/rivy/deno.dxx@v%.%.%'
    - // v%.%.%
  VERSION: '%.%.%'
  src/lib/$shared.ts: const VERSION = '%.%.%';
  # eg/*.ts: 'rivy/deno.dxx@v%.%.%'
  eg/WanCopy.ts: 'rivy/deno.dxx@v%.%.%'
