version: 0.0.12
commit: '%.%.%'
files:
  README.md:
    - 'https://deno.land/x/dxx@v%.%.%'
    - 'https://cdn.jsdelivr.net/gh/rivy/deno.dxx@v%.%.%'
    - // v%.%.%
  VERSION: '%.%.%'
  src/lib/$shared.ts: const VERSION = '%.%.%';
